### ISSUE TITLE
Update codebase for SS4

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/cwp-core#1]
Use namespace ~~`SilverStripe\CWPCore`~~ `CWP\Core`.

Sub-tasks can be added separately or as items in a checklist on this issue.

## Acceptance criteria

- [x] Works on SS4
- [x] Unit tests/CI builds pass
- [x] Code is PSR-2 compliant
- [x] Files are PSR-4 compliant
- [x] Upgrader mapping file is valid
- [x] Language files have been updated
- [x] Transifex config `.tx` file has been removed from SS3 branches and merged up (SS)
- [x] New translations pushed to Transifex
- [x] Beta tag released

## Sub tasks

- [x] Bulk of upgrading work: pull request #6 
- [x] #5 Use middleware over request filters
- [x] #4 Rename SolrSearchIndex to CwpSolrIndex
- [x] #9 Update language files
- [x] PR for TinyMCE plugins at #11 
- [x] Compatibility with subsites and cwp/cwp: #12 
- [x] Starter theme template path adjustments: https://github.com/silverstripe/cwp-starter-theme/pull/13
- [x] Move search functionality to a new module: #14

**Comment by phptek** [comment]
Hey @robbieaverill If there's a better forum for this question, then let me know, but what namespace and dir structure were you thinking of using? 

I'm about to use the following (open to suggestions though)

/home/russellmichell/htdoc/tdc.govt.nz/cwp-core/src
Atom/ (CwpAtomFeed.php)
Config/ (CwpInitialisationFilter.php)
Extension/ (everything that was  under "extensions")
Model/ (everything that was  nder "models")
Report/ (CwpStatsReport.php)
Search/ (CwpSolrConfigStore.php, CwpSolr.php)

**Comment by robbieaverill** [comment]
Hey @phptek - this is the perfect forum for this!

The folder structure looks good to me.

I suggest we use `CWP\Core` as the namespace for this module. We'll use `CWP\CWP` for github.com/silverstripe/cwp.

What do you think?

**Comment by phptek** [comment]
For the namespace `CWP\Core` is _precisely_ what I had just used.

**Comment by robbieaverill** [comment]
Don't forget to use the silverstripe-upgrader tool, or manually create a `.upgrade.yml` file if you don't want to use it

**Comment by phptek** [comment]
@robbieaverill I've had probs with the upgrader (composer related) and TBH I CBA (Google that one!) I figure I'm going to be in each file anyway so...

**Comment by robbieaverill** [comment]
I'm going to work against @phptek's fork which has he's been doing great work on so far, and we will make a PR back to master when it's ready

**Comment by robbieaverill** [comment]
Remaining is to sort out the TinyMCE plugins that have been removed from core in SS4

**Comment by robbieaverill** [comment]
PR for TinyMCE plugins at #11

**Comment by robbieaverill** [comment]
PR for compatibility with subsites and cwp/cwp fixes here: https://github.com/silverstripe/cwp-core/pull/12

**Comment by robbieaverill** [comment]
Beta! https://github.com/silverstripe/cwp-core/releases/tag/2.0.0-beta1
